// Code generated by go-swagger; DO NOT EDIT.

package user_resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersUsingGETParams creates a new GetUsersUsingGETParams object
// with the default values initialized.
func NewGetUsersUsingGETParams() *GetUsersUsingGETParams {

	return &GetUsersUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersUsingGETParamsWithTimeout creates a new GetUsersUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsersUsingGETParamsWithTimeout(timeout time.Duration) *GetUsersUsingGETParams {

	return &GetUsersUsingGETParams{

		timeout: timeout,
	}
}

// NewGetUsersUsingGETParamsWithContext creates a new GetUsersUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUsersUsingGETParamsWithContext(ctx context.Context) *GetUsersUsingGETParams {

	return &GetUsersUsingGETParams{

		Context: ctx,
	}
}

// NewGetUsersUsingGETParamsWithHTTPClient creates a new GetUsersUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUsersUsingGETParamsWithHTTPClient(client *http.Client) *GetUsersUsingGETParams {

	return &GetUsersUsingGETParams{
		HTTPClient: client,
	}
}

/*GetUsersUsingGETParams contains all the parameters to send to the API endpoint
for the get users using g e t operation typically these are written to a http.Request
*/
type GetUsersUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get users using g e t params
func (o *GetUsersUsingGETParams) WithTimeout(timeout time.Duration) *GetUsersUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users using g e t params
func (o *GetUsersUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users using g e t params
func (o *GetUsersUsingGETParams) WithContext(ctx context.Context) *GetUsersUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users using g e t params
func (o *GetUsersUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users using g e t params
func (o *GetUsersUsingGETParams) WithHTTPClient(client *http.Client) *GetUsersUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users using g e t params
func (o *GetUsersUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
