// Code generated by go-swagger; DO NOT EDIT.

package hello_resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHelloPostUsingPOSTParams creates a new HelloPostUsingPOSTParams object
// with the default values initialized.
func NewHelloPostUsingPOSTParams() *HelloPostUsingPOSTParams {
	var ()
	return &HelloPostUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHelloPostUsingPOSTParamsWithTimeout creates a new HelloPostUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHelloPostUsingPOSTParamsWithTimeout(timeout time.Duration) *HelloPostUsingPOSTParams {
	var ()
	return &HelloPostUsingPOSTParams{

		timeout: timeout,
	}
}

// NewHelloPostUsingPOSTParamsWithContext creates a new HelloPostUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewHelloPostUsingPOSTParamsWithContext(ctx context.Context) *HelloPostUsingPOSTParams {
	var ()
	return &HelloPostUsingPOSTParams{

		Context: ctx,
	}
}

// NewHelloPostUsingPOSTParamsWithHTTPClient creates a new HelloPostUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHelloPostUsingPOSTParamsWithHTTPClient(client *http.Client) *HelloPostUsingPOSTParams {
	var ()
	return &HelloPostUsingPOSTParams{
		HTTPClient: client,
	}
}

/*HelloPostUsingPOSTParams contains all the parameters to send to the API endpoint
for the hello post using p o s t operation typically these are written to a http.Request
*/
type HelloPostUsingPOSTParams struct {

	/*Hello
	  hello

	*/
	Hello string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the hello post using p o s t params
func (o *HelloPostUsingPOSTParams) WithTimeout(timeout time.Duration) *HelloPostUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the hello post using p o s t params
func (o *HelloPostUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the hello post using p o s t params
func (o *HelloPostUsingPOSTParams) WithContext(ctx context.Context) *HelloPostUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the hello post using p o s t params
func (o *HelloPostUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the hello post using p o s t params
func (o *HelloPostUsingPOSTParams) WithHTTPClient(client *http.Client) *HelloPostUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the hello post using p o s t params
func (o *HelloPostUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHello adds the hello to the hello post using p o s t params
func (o *HelloPostUsingPOSTParams) WithHello(hello string) *HelloPostUsingPOSTParams {
	o.SetHello(hello)
	return o
}

// SetHello adds the hello to the hello post using p o s t params
func (o *HelloPostUsingPOSTParams) SetHello(hello string) {
	o.Hello = hello
}

// WriteToRequest writes these params to a swagger request
func (o *HelloPostUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Hello); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
