// Code generated by go-swagger; DO NOT EDIT.

package hello_resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new hello resource API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for hello resource API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	HelloPostUsingPOST(params *HelloPostUsingPOSTParams) (*HelloPostUsingPOSTOK, *HelloPostUsingPOSTCreated, error)

	HelloPutUsingPUT(params *HelloPutUsingPUTParams) (*HelloPutUsingPUTOK, *HelloPutUsingPUTCreated, error)

	HelloUsingGET(params *HelloUsingGETParams) (*HelloUsingGETOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  HelloPostUsingPOST returns hello world
*/
func (a *Client) HelloPostUsingPOST(params *HelloPostUsingPOSTParams) (*HelloPostUsingPOSTOK, *HelloPostUsingPOSTCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelloPostUsingPOSTParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "helloPostUsingPOST",
		Method:             "POST",
		PathPattern:        "/rest/hello/post",
		ProducesMediaTypes: []string{"*/*"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &HelloPostUsingPOSTReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *HelloPostUsingPOSTOK:
		return value, nil, nil
	case *HelloPostUsingPOSTCreated:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for hello_resource: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  HelloPutUsingPUT returns hello world
*/
func (a *Client) HelloPutUsingPUT(params *HelloPutUsingPUTParams) (*HelloPutUsingPUTOK, *HelloPutUsingPUTCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelloPutUsingPUTParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "helloPutUsingPUT",
		Method:             "PUT",
		PathPattern:        "/rest/hello/put",
		ProducesMediaTypes: []string{"*/*"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &HelloPutUsingPUTReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *HelloPutUsingPUTOK:
		return value, nil, nil
	case *HelloPutUsingPUTCreated:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for hello_resource: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  HelloUsingGET returns hello world
*/
func (a *Client) HelloUsingGET(params *HelloUsingGETParams) (*HelloUsingGETOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelloUsingGETParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "helloUsingGET",
		Method:             "GET",
		PathPattern:        "/rest/hello",
		ProducesMediaTypes: []string{"*/*"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &HelloUsingGETReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelloUsingGETOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for helloUsingGET: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
