// Code generated by go-swagger; DO NOT EDIT.

package hello_resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHelloPutUsingPUTParams creates a new HelloPutUsingPUTParams object
// with the default values initialized.
func NewHelloPutUsingPUTParams() *HelloPutUsingPUTParams {
	var ()
	return &HelloPutUsingPUTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHelloPutUsingPUTParamsWithTimeout creates a new HelloPutUsingPUTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHelloPutUsingPUTParamsWithTimeout(timeout time.Duration) *HelloPutUsingPUTParams {
	var ()
	return &HelloPutUsingPUTParams{

		timeout: timeout,
	}
}

// NewHelloPutUsingPUTParamsWithContext creates a new HelloPutUsingPUTParams object
// with the default values initialized, and the ability to set a context for a request
func NewHelloPutUsingPUTParamsWithContext(ctx context.Context) *HelloPutUsingPUTParams {
	var ()
	return &HelloPutUsingPUTParams{

		Context: ctx,
	}
}

// NewHelloPutUsingPUTParamsWithHTTPClient creates a new HelloPutUsingPUTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHelloPutUsingPUTParamsWithHTTPClient(client *http.Client) *HelloPutUsingPUTParams {
	var ()
	return &HelloPutUsingPUTParams{
		HTTPClient: client,
	}
}

/*HelloPutUsingPUTParams contains all the parameters to send to the API endpoint
for the hello put using p u t operation typically these are written to a http.Request
*/
type HelloPutUsingPUTParams struct {

	/*Hello
	  hello

	*/
	Hello string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the hello put using p u t params
func (o *HelloPutUsingPUTParams) WithTimeout(timeout time.Duration) *HelloPutUsingPUTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the hello put using p u t params
func (o *HelloPutUsingPUTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the hello put using p u t params
func (o *HelloPutUsingPUTParams) WithContext(ctx context.Context) *HelloPutUsingPUTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the hello put using p u t params
func (o *HelloPutUsingPUTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the hello put using p u t params
func (o *HelloPutUsingPUTParams) WithHTTPClient(client *http.Client) *HelloPutUsingPUTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the hello put using p u t params
func (o *HelloPutUsingPUTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHello adds the hello to the hello put using p u t params
func (o *HelloPutUsingPUTParams) WithHello(hello string) *HelloPutUsingPUTParams {
	o.SetHello(hello)
	return o
}

// SetHello adds the hello to the hello put using p u t params
func (o *HelloPutUsingPUTParams) SetHello(hello string) {
	o.Hello = hello
}

// WriteToRequest writes these params to a swagger request
func (o *HelloPutUsingPUTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Hello); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
