// Code generated by go-swagger; DO NOT EDIT.

package hello_resource

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHelloUsingGETParams creates a new HelloUsingGETParams object
// with the default values initialized.
func NewHelloUsingGETParams() *HelloUsingGETParams {

	return &HelloUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHelloUsingGETParamsWithTimeout creates a new HelloUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHelloUsingGETParamsWithTimeout(timeout time.Duration) *HelloUsingGETParams {

	return &HelloUsingGETParams{

		timeout: timeout,
	}
}

// NewHelloUsingGETParamsWithContext creates a new HelloUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewHelloUsingGETParamsWithContext(ctx context.Context) *HelloUsingGETParams {

	return &HelloUsingGETParams{

		Context: ctx,
	}
}

// NewHelloUsingGETParamsWithHTTPClient creates a new HelloUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHelloUsingGETParamsWithHTTPClient(client *http.Client) *HelloUsingGETParams {

	return &HelloUsingGETParams{
		HTTPClient: client,
	}
}

/*HelloUsingGETParams contains all the parameters to send to the API endpoint
for the hello using g e t operation typically these are written to a http.Request
*/
type HelloUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the hello using g e t params
func (o *HelloUsingGETParams) WithTimeout(timeout time.Duration) *HelloUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the hello using g e t params
func (o *HelloUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the hello using g e t params
func (o *HelloUsingGETParams) WithContext(ctx context.Context) *HelloUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the hello using g e t params
func (o *HelloUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the hello using g e t params
func (o *HelloUsingGETParams) WithHTTPClient(client *http.Client) *HelloUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the hello using g e t params
func (o *HelloUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HelloUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
